### ISSUE TITLE
adding column for cured people in Europe wikipedia

### ISSUE THREAD

**Issue by lenzai** [coderbunker/COVID-19-scraper#4]
Currently the aggregation for Wikipedia Europe is publishing only sick and dead people.

```
Country | Region | Date | sick | dead | sick | dead
```
We wish to expose also the recovered/remaining cases (one of them)

Acceptance criteria:
- sheet "<Wikipedia - Europe" contains final data
- layout is consistent with sheet "<master - source"

**Comment by ansufei** [comment]
Done

**Comment by lenzai** [comment]
move it to reviewing in project board and don't close the issue without
getting feedback from 1 peer
